# Utilisez une image de node.js
FROM node:18

# Définissez le répertoire de travail
WORKDIR /Back

# Copiez les fichiers nécessaires
COPY package*.json ./

# Installez les dépendances
RUN npm install

RUN npm install sqlite3

# Copiez le reste des fichiers
COPY . .

# Execution des migrations
RUN npm run migrate

# Exposez le port utilisé par votre application
EXPOSE 3000

# Commande pour démarrer votre application après les migrations
CMD ["npm", "start"]