name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # Voir le calendrier de sortie de Node.js pris en charge sur https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
      env:
        NODE_OPTIONS: '--max-old-space-size=4096'
      working-directory: ./Back
    - name: Build
      run: npm run build --if-present
      working-directory: ./Back
    - name: Test
      run: npm test
      working-directory: ./Back
